In [ ]:
##numpy , pandas , matplotlib, seaborn  --- third party library
#pip -- package manager 
##pip install numpy 

##numpy -- numerical python 
##mathematical operations 
##linear algebra 
##array
#array -- data type 
# diff array vs list 
# list - mutiple data types 
#array - single data type
##same list --- [1,2,"jai",True]
# array - [1,2,3,4,5] 

#array -- dimension
##1d array --- single list -- []
##2d array -- list of lists -- [[]]
##3d array -- list of 2d array -- [[[]]]
##nd array 


In [ ]:
##how to make an array 
import numpy as np  #alias // nickname 

In [5]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [6]:
#range(1,10) -- 1 to 9
arr2 = np.arange(1,100,2)
arr2


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [13]:
#matrix -- [1 ,1 ,1 ,1 ] , [0,0,0,]
#ones array
# arr3 = np.ones(10)
# arr3 = np.zeros(10)
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
#linespace --- 1 to 10 -- range define  --- 5 elements
arr4 = np.linspace(1,10,50)
arr4

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [12]:
##2d array -- list of lists -- matrix -- rows and columns -- 
#shape -- m x n -- m rows and n columns
arr5 = np.array([[1,2,4],[4,5,6]])
arr5

array([[1, 2, 4],
       [4, 5, 6]])

In [15]:
## 1d --> 2d -- reshape -- shape change 
arr6 = np.arange(1,31).reshape(6,5)
arr6

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [29]:
##random module -- random numbers generation 
# arr7 = np.random.randint(1,100,10)
# arr7 = np.random.randint(1,100,(2,3))
arr7 = np.random.random(10)
arr7.dtype

dtype('float64')

In [27]:
## 2d array -- 60 elements 
arr8 = np.arange(1,61).reshape(6,10)
arr8.shape 
arr8.size
arr8.dtype
arr8.ndim

2

In [30]:
##nd array convert to 1d array 
arr8.ravel()
arr8.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [33]:
##transpose --- array shape reverse-- -
##(2,4) -- (4,2)
print(arr8.shape)
arr8.T.shape

(6, 10)


(10, 6)

In [40]:
##accessing elemnts from array 
##1d  -- single list 
arr2 = np.arange(1,10)
##siling  -- multiple elements access 
#[start : end : step]
arr2[3:4]


array([4])

In [42]:
##2d array -- [row start :row end:row skip , column start : column end : column skip]
arr6 = np.arange(1,31).reshape(6,5)
arr6

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [48]:
arr6[1:2,2:3][0][0]

8

In [ ]:
#3d array (table , row ,col)
arr6 = np.arange(1,31).reshape(2,3,5)
arr6


array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [50]:
arr7 = np.random.randint(1,10,(2,3,4))
arr7

array([[[6, 1, 9, 6],
        [2, 9, 6, 8],
        [5, 5, 4, 3]],

       [[2, 2, 8, 7],
        [1, 6, 6, 2],
        [9, 1, 3, 8]]])

In [ ]:
##MATHEMATIC OPERATIONS
##note -- both array should be of same shape 
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 % arr2)
print(arr1 // arr2)
print(arr1 ** arr2)
print(arr1 > arr2)
print(arr1 < arr2)
print(arr1 == arr2)
print(arr1 != arr2)
print(arr1 >= arr2)
print(arr1 <= arr2)

[ 5  7  9 11 13 15]
[-3 -3 -3 -3 -3 -3]
[ 4 10 18 28 40 54]
[0.25       0.4        0.5        0.57142857 0.625      0.66666667]
[1 2 3 4 5 6]
[0 0 0 0 0 0]
[       1       32      729    16384   390625 10077696]
[False False False False False False]
[ True  True  True  True  True  True]
[False False False False False False]
[ True  True  True  True  True  True]
[False False False False False False]
[ True  True  True  True  True  True]
